In [1]:
### 01. 데이터 준비
import pandas as pd
data = { "eng": ["b", "c", "a", "d"] }
df = pd.DataFrame(data)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


eng
0   b
1   c
2   a
3   d

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
en_x = LabelEncoder()
df['LabelEncoding'] = en_x.fit_transform(df['eng'])

In [4]:
df

eng  LabelEncoding
0   b              1
1   c              2
2   a              0
3   d              3

In [6]:
onehot = OneHotEncoder()
val = df['LabelEncoding'].values.reshape(-1,1)
type(val), val.shape

(numpy.ndarray, (4, 1))

In [7]:
y = onehot.fit_transform( val ).toarray()  
y

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [8]:
onehot_val = pd.DataFrame(y, dtype=int)
print(onehot_val)

df_new = pd.concat([df, onehot_val], axis=1)
df_new

   0  1  2  3
0  0  1  0  0
1  0  0  1  0
2  1  0  0  0
3  0  0  0  1


eng  LabelEncoding  0  1  2  3
0   b              1  0  1  0  0
1   c              2  0  0  1  0
2   a              0  1  0  0  0
3   d              3  0  0  0  1

In [9]:
data = { "회사명": ["MS","Apple", "Google", "Google"]}
df1 = pd.DataFrame(data)
df2 = df1.copy()
df2

회사명
0      MS
1   Apple
2  Google
3  Google

In [11]:
en_x = LabelEncoder()
df2['LabelEncoding'] = en_x.fit_transform(df2['회사명'])

In [12]:
onehot = OneHotEncoder()
val = df2['LabelEncoding'].values.reshape(-1,1)
val

array([[2],
       [0],
       [1],
       [1]])

In [13]:
y = onehot.fit_transform( val ).toarray()  
y

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [15]:
onehot_val = pd.DataFrame(y, dtype=int)
onehot_val

0  1  2
0  0  0  1
1  1  0  0
2  0  1  0
3  0  1  0

In [16]:
df2_new = pd.concat([df2, onehot_val], axis=1)
df2_new

회사명  LabelEncoding  0  1  2
0      MS              2  0  0  1
1   Apple              0  1  0  0
2  Google              1  0  1  0
3  Google              1  0  1  0